name = "SchurParlett"
uuid = "19a19067-98a7-4934-96a9-4ffe4c335fa4"
authors = ["Errol Seders"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
